# Generated by Django 4.0.5 on 2022-07-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('artist', models.CharField(max_length=32)),
                ('year', models.IntegerField()),
                ('cover', models.CharField(max_length=32)),
            ],
        ),
    ]
